# ----
# Site

title: SaaSitive
url: "https://saasitive.com"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:


logo: /siteicon.png
description: Empower Dreamers
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: SaaSitive
  links:
    - https://github.com/saasitive


markdown: kramdown
highlighter: rouge
input: GFM

# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: "/blog/:title/"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  -
    scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
  -
    scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

emoji:
  src: "https://github.githubassets.com/images/icons/"